/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Continuity-Camera.h
 #	source generated by 4D Plugin Wizard
 #	Project : Continuity Camera
 #	author : miyako
 #	2021/09/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_CONTINUITY_CAMERA_H
#define PLUGIN_CONTINUITY_CAMERA_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#import <Cocoa/Cocoa.h>
#import <objc/runtime.h>
#import <AppKit/AppKit.h>
#include "tiffio.h"

#pragma mark -

static void Continuity_camera_menu(PA_PluginParameters params);

#endif /* PLUGIN_CONTINUITY_CAMERA_H */
